repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-docstring-first
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        entry: bash -c "cd server && black src --check"

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        entry: bash -c "cd server && isort src --check"

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        entry: bash -c "cd server && flake8"
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-simplify

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        entry: bash -c "cd server && bandit -ll -r src"
