from prettyconf import config

STAGE = config("STAGE")

AWS_DEFAULT_REGION = config("AWS_DEFAULT_REGION")
AWS_BUCKET_NAME = config("AWS_BUCKET_NAME")
AWS_DYNAMODB_TABLE_NAME = config("AWS_DYNAMODB_TABLE_NAME")
