name: Server Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  server_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Setup Dev Environment
        run: make build-dev

      - name: Run Dev Container
        run: make run-dev

      - name: Run Checks
        run: make check

      - name: Run Tests
        run: make test
