name: Pipeline
env:
  DOCKER_REGISTRY: 135180784361.dkr.ecr.us-east-1.amazonaws.com/url-service-dev
  INFRA_BASE_PATH: infra/resources

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  server_test:
    name: Server Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Build Dev Container
        run: make build-dev

      - name: Run Dev Container
        run: make run-dev

      - name: Run Checks
        run: make check

      - name: Run Tests
        run: make test

  infra_test:
    name: Infra Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run Checks
        run: |
          cd ${{ env.INFRA_BASE_PATH }}
          terraform init
          terraform workspace select dev
          terraform fmt -check
          terraform validate -no-color

  server_deploy:
    name: Server Deploy
    runs-on: ubuntu-latest
    needs: [server_test, infra_test]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Add image tag
        run: echo "IMAGE_TAG=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Build and push container to Amazon ECR
        run: |
          docker build -t $DOCKER_REGISTRY:$IMAGE_TAG .
          docker push $DOCKER_REGISTRY:$IMAGE_TAG
          echo "TF_VAR_lambda_image_uri=$DOCKER_REGISTRY:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.5

      - name: Apply Terraform
        run: |
          cd ${{ env.INFRA_BASE_PATH }}
          terraform init
          terraform workspace select dev
          terraform apply --auto-approve
